### ISSUE TITLE
ANT is always found by buildsystem, even if it is not available

### ISSUE THREAD

**Issue by dkoole** [AgileManufacturing/HUniversal-Production-Utrecht#11]
Ant is always found by CMake, even if it is not installed on the development PC. It is caused by the file cmake/FindANT.cmake

**Comment by pascalmuller** [comment]
This is not possible, unless something is wrong with CMake. 

FIND_PROGRAM(ANT_FOUND  NAMES "ant"..... should set ANT_FOUND. According to the CMake documentation ( http://www.cmake.org/cmake/help/cmake2.6docs.html#command:find_program ) this should set ANT_FOUND to ANT_FOUND-NOTFOUND. Variables ending in -NOTFOUND always evaluate to false. If the other parts of the buildsystem check ANT_FOUND, it should evaluate to false if ant is not available on the system. 

Maybe the checks if ANT_FOUND is true are wrong?
