### ISSUE TITLE
Bug in statemachine

### ISSUE THREAD

**Issue by KBraham** [AgileManufacturing/HUniversal-Production-Utrecht#23]
Each node that implements a statemachine is running at 100% cpu cycles. This is caused by the while(ros::ok()){ ros::spinOnce();} loop.  To solve this issue I guess a ros::rate has to be used?

Unfortunately, the ros wiki is down right now so I can't lookup for the correct way to handle this...

(and the pentium pc keeps heating up)

**Comment by arjanhgroen** [comment]
With ros::rate we can control the frequency of the spinning but I am not sure this is what we want, not every module will have the same frequency. So we either just remove the while loop and let every node that implements a State Machine handle it ros::spin or the option for rate should be added to the loop. 

And I think ROS is designed this way, to run full throttle so it can handle every callback as quikly as possible
